export enum CallerCategory {
    EC_CALLER = 'EC_CALLER',
    HT_CALLER = 'HT_CALLER',
    WEBSITE_CALLER = 'WEBSITE_CALLER',
    POPIN_CALLER = 'POPIN_CALLER',
    INTERNATIONAL_CALLER = 'INTERNATIONAL_CALLER',
}
